<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>$(NoWarn);CS8981</NoWarn> <!-- Disabling EF Core warn -->
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DomainScanner.Domain\DomainScanner.Domain.csproj" />
        <ProjectReference Include="..\DomainScanner.Application\DomainScanner.Application.csproj" />
    </ItemGroup>

</Project>
