services:
  postgres-database:
    image: postgres:18-alpine
    environment:
      - POSTGRES_DB=scannerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scannerdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - backend-domainscanner
      
  aspnet-api:
    image: api
    build:
      context: ../.
      dockerfile: backend/src/DomainScanner.Api/Dockerfile
    depends_on:
      postgres-database:
        condition: service_healthy
    environment:
      ConnectionStrings__PostgresConnection: Host=postgres-database;Port=5432;Database=scannerdb;Username=postgres;password=postgres
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend-domainscanner
    
  hangfire-worker:
    image: worker
    build:
      context: ../.
      dockerfile: backend/src/DomainScanner.Worker/Dockerfile
    depends_on:
      postgres-database:
        condition: service_healthy
    environment:
      ConnectionStrings__PostgresConnection: Host=postgres-database;Port=5432;Database=scannerdb;Username=postgres;password=postgres
      DomainChecksWorker__CronExpression: "*/5 * * * *"
      DomainChecksWorker__QueueName: domain-checks
      DomainChecksWorker__BatchSize: 30
    networks:
      - backend-domainscanner

volumes:
  postgres-data:
    driver: local
    name: domains-postgres-data
  

networks:
  backend-domainscanner:
    driver: bridge